package edu.poly.common;

public enum PageType {
	USER_MANAGEMENT_PAGE, REPORTS_MANAGEMENT_PAGE, VIDEOS_MANAGEMENT_PAGE, SITE_HOME_PAGE, SITE_LOGIN_PAGE,
	SITE_REGISTRATION_PAGE, SITE_CHANGEPASSWORD_PAGE, SITE_FORGOTPASSWORD_PAGE, SITE_EDITPROFILE_PAGE, VIDEO_SHARE_PAGE,
	VIDEO_FAVORITES_PAGE, VIDEO_DETAIL_PAGE
}
